/*
 *  Copyright (C) 2004-2006  Michael Feiner
 *
 */

#ifndef MDC_DIGIO_H
#define MDC_DIGIO_H

#include <dev/digout.h>
#include <dev/digin.h>

/** @addtogroup arch
 *
 * @{
 */

/** @defgroup digio digio.h
 *
 * Digital Input,Output.
 *
 * @{
 */


/** Run Led */
extern DEV_digout_t MDC_run_led;

/** Ethernet Chip Reset */
extern DEV_digout_t MDC_eth_reset;

/** Control Led 1 */
extern DEV_digout_t MDC_red_led;

/** Control Led 2 */
extern DEV_digout_t MDC_green_led;

/** LCD Backlight on/off */
extern DEV_digout_t MDC_lcd_backlight;


/** Button */
extern DEV_digin_t MDC_button;

/** Jumper 1 */
extern DEV_digin_t MDC_yellow;

/** Jumper 2 */
extern DEV_digin_t MDC_green;

/** Jumper 3 */
extern DEV_digin_t MDC_blue;

/** Jumper 4 */
extern DEV_digin_t MDC_red;

/** Signal generated by a random generator */
extern DEV_digin_t MDC_random_signal;

/** Switch */
extern DEV_digin_t MDC_switch;

/** Control inputs */
extern DEV_diginputs_t MDC_control_in;

/**
 * Initialize digital io.
 */
extern void MDC_digio_init (void);

/**
 * Register digital io in sysfs.
 */
extern void MDC_digio_install (void);

/** @}
 */

/** @}
 */

#endif
