-include $(MOST_ROOT)/etc/Config

LIB_NAME := act
LIB_TYPE := usr
OBJ_NAMES := motor/$(MOST_BUILD)/o/$(MOST_TARGET_TYPE)/*.o

makegoal = make $(1) -C motor;

-include $(MOST_ROOT)/etc/build/lib/Makefile
