makegoal = make $(1) -C ace;\
	       make $(1) -C uso;\
	       make $(1) -C dev;\
	       make $(1) -C net;\
	       make $(1) -C nap;\
	       make $(1) -C mfs;\
	       make $(1) -C cli;

-include $(MOST_ROOT)/etc/build/libs/Makefile
