-include $(MOST_ROOT)/etc/Config
-include $(MOST_ROOT)/etc/Commands

export LIB_NAME LIB_TYPE OBJ_NAMES

.PHONY : default help lib obj clean mrproper

default:
	@$(ECHO) "Please use <make help> for more information."

help :
	@$(call makegoal, help)
	@$(ECHO) ""
	@$(ECHO) "---------------------- Makefile.lib -------------------------------------------------------"
	@$(ECHO) "Build the most lib $(LIB_NAME)."
	@$(ECHO) "---------------------"
	@$(ECHO) "help          : goal"
	@$(ECHO) "obj		: goal"
	@$(ECHO) "lib	       	: obj, build"
	@$(ECHO) "clean		: goal, build, rm ../lib/$(MOST_TARGET)/lib_$(LIB_NAME).a"
	@$(ECHO) "mrproper	: clean, goal"
	@$(ECHO) "---------------------------------------------------------------------------------------------"
	@$(ECHO) ""

lib : obj
	@make $@ --no-print-directory -f $(MOST_ROOT)/etc/Makefile.build

obj :
	@$(call makegoal, $@)

clean : 
	@$(call makegoal, $@)
	@make $@ --no-print-directory -f $(MOST_ROOT)/etc/Makefile.build
	-$(REMOVE) ../lib/$(MOST_TARGET)/lib_$(LIB_NAME).a

mrproper : clean
	@$(call makegoal, $@)
	-$(REMOVE) ../lib/$(MOST_TARGET)
