-include $(MOST_ROOT)/etc/Config

LIB_NAME := tst
LIB_TYPE := usr
OBJ_NAMES := basic/$(MOST_BUILD)/o/$(MOST_TARGET_TYPE)/*.o

makegoal = make $(1) -C basic;

-include $(MOST_ROOT)/etc/build/lib/Makefile
