-include $(MOST_ROOT)/etc/Config

LIB_NAME := sen
LIB_TYPE := usr
OBJ_NAMES := groove/$(MOST_BUILD)/o/$(MOST_TARGET_TYPE)/*.o

makegoal = make $(1) -C groove;

-include $(MOST_ROOT)/etc/build/lib/Makefile
